[#ftl]
[#-- @implicitly included --]

[#-- @ftlvariable name="model" type="org.springframework.ui.ModelMap" --]
[#-- @ftlvariable name="booking" type="booking.domain.Booking" --]
[#-- @ftlvariable name="ticket" type="booking.domain.Ticket" --]
[#-- @ftlvariable name="tickets" type="java.util.List<booking.domain.Ticket>" --]
[#-- @ftlvariable name="header" type="java.lang.String" --]
[#-- @ftlvariable name="errorMessage" type="java.lang.String" --]
[#-- @ftlvariable name="event" type="booking.domain.Event" --]
[#-- @ftlvariable name="user" type="booking.domain.User" --]
[#-- @ftlvariable name="auditorium" type="booking.domain.Auditorium" --]
[#-- @ftlvariable name="statics" type="freemarker.template.TemplateHashModel" --]
[#-- @ftlvariable name="statics['booking.web.controller.AuditoriumController'].LOGIN_ENDPOINT" type="java.lang.String" --]
[#-- @ftlvariable name="statics['booking.web.controller.AccountController'].ROOT_ENDPOINT" type="java.lang.String" --]
[#-- @ftlvariable name="statics['booking.web.controller.BookingController'].ROOT_ENDPOINT" type="java.lang.String" --]
[#-- @ftlvariable name="statics['booking.web.controller.LoginController'].LOGIN_ENDPOINT" type="java.lang.String" --]
[#-- @ftlvariable name="statics['booking.web.controller.UserController'].REGISTER_ENDPOINT" type="java.lang.String" --]
[#-- @ftlvariable name="statics['org.springframework.http.MediaType'].APPLICATION_FORM_URLENCODED_VALUE" type="java.lang.String" --]
[#-- @ftlvariable name="statics['booking.web.controller.EventController'].LOGIN_ENDPOINT" type="java.lang.String" --]

[#function currentUser][/#function]
[#function currentAccount][/#function]